fn main() {
    println!("Hello comments!");

    // This is a single line comment

    /*  We can create multiple lines
        comments like these ones
    */


    /// We can create documentation comments
    /// These lines are added to the documentation generated by rustdoc
    /// Example of doc comments
    let a: i32 = 100;

    println!("Variable value is {}", a);
}
